# Generated by Django 5.0.6 on 2024-06-04 03:40

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("email", models.EmailField(max_length=40, unique=True)),
                ("username", models.CharField(max_length=16, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("f_name", models.CharField(max_length=16)),
                ("l_name", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
