# Generated by Django 5.0.6 on 2024-06-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rough_draft", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="matchpick",
            table="match_pick",
        ),
    ]
