# Generated by Django 5.0.6 on 2024-06-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Golfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_id", models.CharField(max_length=10)),
                ("f_name", models.CharField(max_length=16)),
                ("l_name", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_id", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=4)),
                ("golf_course", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("par", models.IntegerField(blank=True, null=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("week_number", models.CharField(max_length=3)),
                ("time_zone", models.CharField(blank=True, max_length=20, null=True)),
                ("major_championship", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
