# Generated by Django 5.0.6 on 2024-07-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("call_caddy", "0002_alter_golfer_table_alter_tournament_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="format",
            field=models.CharField(default="stroke", max_length=20),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="golf_course",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="par",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="time_zone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="year",
            field=models.IntegerField(),
        ),
    ]
