# Generated by Django 5.0.6 on 2024-07-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("call_caddy", "0003_tournament_format_alter_tournament_golf_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="location",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="week_number",
            field=models.IntegerField(),
        ),
    ]
