# Generated by Django 5.0.6 on 2024-07-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("call_caddy", "0004_alter_tournament_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="tournament_id",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="f_name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="l_name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="source_id",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="source_id",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(fields=["tournament_id", "year"], name="tournament_id_year_idx"),
        ),
    ]
