# Generated by Django 5.0.6 on 2024-07-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("call_caddy", "0005_tournament_tournament_id_alter_golfer_f_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="golfer",
            name="last_active_tourney",
            field=models.CharField(default="12223456abcdef", max_length=100),
            preserve_default=False,
        ),
    ]
