# Generated by Django 5.0.6 on 2024-06-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scorecard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="matchresult",
            table="match_result",
        ),
        migrations.AlterModelTable(
            name="score",
            table="score",
        ),
    ]
