# Generated by Django 5.0.6 on 2024-06-04 03:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("call_caddy", "0001_initial"),
        ("grounds_crew", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchPick",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("priority", models.IntegerField()),
                ("drafted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "golfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="match_pick", to="call_caddy.golfer"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_pick",
                        to="call_caddy.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="match_pick", to="grounds_crew.user"
                    ),
                ),
            ],
        ),
    ]
